# BME-336546-C01-Python, numpy and friends 🐍

## Introduction

Python is a great general-purpose programming language on its own and with the addition of a few
popular libraries such as `numpy`, `pandas`, `scikit-learn`, `matplotlib` and others it becomes an
effective scientific computing environment.



Python has great [documentation](https://docs.python.org/3)! Use it often.

In this tutorial, we will cover:
* What is an IDE?
* Breif hierarchy in Python.
* Environment setup with `conda`.
* Python overview: Basic data structures, itertables and functions' features.
* Numpy: Arrays, Array indexing, Datatypes and Array math.

## IDE: Integrated Development Environment

For our purposes, IDE is simply our editor. In contrary to Matlab, which is both the interpreter (the language) and the editor, for running Python we have multiple options. Familiar IDEs are “*Py*Charm”, “S*py*der” and “Ju*py*ter NoteBook”. Each with its own pros and cons.

Ju*py*ter, for instance, is very useful for tutorials/workshops such as this one since it can have both text (Markdown cells) including mathematical graphic syntax (using Latex) and run code (in code cells). However, we cannot debug on Ju*py*ter.


Moreover, those IDEs can run multiple interpreters of Python for different versions. 
In opposite to Matlab, Python comes with a basic set of packages and any other one will have to be imported as you will see up next.


The *console* in the IDE is simply the command line (as in Matlab) and the *terminal* is the command prompt. 

## Hierarchy in Python: packages, modules and virtual environments

A python *module* is simply a python file (`.py`), which can contain functions, classes and even top-level code. It is analogues to a script in Matlab. You will build modules. A module can be imported and can import others.

A *package* is a collection of `modules` within a directory. Python comes with a standard library which
includes many useful packages. A package can be imported. You will not build packages in this course, only import existing ones.
They can be imported like so:

In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))

# Several options to import python standard library
import sys
import random
import math as mt
from math import ceil as ce

print(f'A random number in [3 9] for exapmle is: ', random.uniform(3,9))
print(mt.pi)
p = 2.4
print(mt.floor(p))
print(ce(p))

A random number in [3 9] for exapmle is:  8.565555629628376
3.141592653589793
2
3


An *environment* is an `.exe` file that contains multiple *packages*. It is used to guide your project to have an access only to packages that are in the environment. It is also used to distinguish between versions of Python. 

**Notice:** This kind of environment has nothing to do with the (development) environment that we have defined in IDE.

## Environment setup

In order to build an environment we need a *package manager*. A package manager is responsible to create the environment, to install/uninstall any package in it and of course activating it. We will use a package manager that is called `Conda`.

*Anaconda* or *Miniconda* are softwares where all packages of python exist in. \
The first way to create and activate an environment is through the IDE itself. \
The second way is through the Anaconda prompt using the commands that are shown in this [cheatsheet](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf).

- All of the tutorials would use an environment called `bm-336546`. It will be installed once and then would be updated almost every tutorial as needed. Both installation and updates would be performed by using yml files which define which third-party libraries we depend on.
- Conda will use this file to create a virtual environment for you.
- This virtual environment includes python and all other packages and tools we specified, separated from any pre-existing python installation you may have.

### Installation

Install all dependencies with `conda`:

First open anaconda prompt and use `cd` command to change working directory to the location where you have saved your yml file.

To create the environment:
```shell
conda env create --file bm-336546.yml
```

**This installation should be only performed once!**

To activate the virtual environment:

```shell
conda activate bm-336546
```
If you would like to return to `(base)` environment type:
```shell
conda deactivate
```
You should now see on the left of the working directory path the name of the environment as follows `(bm-336546)`. Notice that from now on you can activate the environment from any directory in anaconda prompt.

To check what conda environments you have and which one is active, run

```shell
conda env list
```
The active environmet would have a `*` next to it.\
In order to **update** the environment with other pacakages that would appear in later yml files you should enter anaconda prompt. Make sure you are on `(base)` environment and then change the directory to where you saved your new yml file (`tutorial2.yml` for instance) using `cd`. Run the following **update** command (in contrary to "create" we saw before):

```shell
conda env update --name bm-336546 --file tutorial2.yml
``` 
After activation of `bm-336546` you can see the new packages added by calling `conda list`.

If for some reason, you mannaged to install the environment but it has some unexpected errors that require to remove the environment and reinstall it, you will need to be on the `(base)` environment and type:
```shell
conda env remove --name bm-336546
```
Then, you can reinstall it as before.

### Running Jupyter

Make sure that the active conda environment is `bm-336546`, and run

```shell
jupyter lab
```

This will start a [jupyter lab](https://jupyterlab.readthedocs.io/en/stable/)
server and open your browser at the local server's url. You can now start working with the notebooks.

**Your Anaconda prompt has to keep working in the background**.

If you're new to jupyter notebook, you can get started by reading the
[UI guide](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html#notebook-user-interface)
and also about how to use notebooks in
[JupyterLab](https://jupyterlab.readthedocs.io/en/latest/user/notebook.html).


#### Jupyter basics

Jupyter notebooks consist mainly of code and markdown cells.
The code cells contain code that is run by a `kernel`, an
interpreter for some programming language, python in our case. For short help documentation in `Jupyter`, simply press `shift+tab` within the circular parantheses.

## Basic data types

### Numbers

Integers and floats work as you would expect from other languages:

In [3]:
x = 3
print(x, type(x))

3 <class 'int'>


In [4]:
x = 5
print(x)
x += 1
print(x)
x -= 2
print(x)
x *= 8
print(x)
x /= 3
print(x)
x //= 4 # Floor division
print(x)

5
6
4
32
10.666666666666666
2.0


Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-long-complex). 


### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [5]:
t, f = True, False

Now we let's look at the operations:

In [6]:
print(t and f) # Logical AND
print(t or f ) # Logical OR
print(not t  ) # Logical NOT
print(t != f ) # Logical XOR

False
True
False
True


### Strings

In [7]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
combined = '"hello world"'  # it can be used to print " " or ' '
print(combined)
hello, combined, len(hello)

"hello world"


('hello', '"hello world"', 5)

In [8]:
# String concatenation
'aaa ' + 'bbb'

'aaa bbb'

There are several ways to create formatted strings, here are some of them:

In [9]:
s = 'hello'
a = [1,2,3]

# sprintf style string formatting
print('%s %s: pi=%.5f' % (s, a, mt.pi))

# format function:
print("{} {}: pi={:.5f}".format(s, a, mt.pi))

# formatting with f-string literals (python 3.6+)
print(f'{s} {a}: pi={mt.pi:.5f}')

hello [1, 2, 3]: pi=3.14159
hello [1, 2, 3]: pi=3.14159
hello [1, 2, 3]: pi=3.14159


String objects have a bunch of useful methods; for example:

In [10]:
s = "hello"
print(s.capitalize() ) # Capitalize a string; prints "Hello"
print(s.upper()      ) # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7)     ) # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7)    ) # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


You can find a list of all string methods in this [documentation](https://docs.python.org/3/library/stdtypes.html#string-methods).

## Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.\
**Notice:** **indexing in Python starts at 0** but it does not include the last number when taking a range, e.g. 0:3 means 0,1,2 and not 0,1,2,3. 

### Lists

A list is the Python equivalent to an array (**not** a mathematical one), but is resizeable and can contain elements of different types:

In [11]:
xs = [3, 1, 2]   # Create a list
print(xs)
print(xs[2], xs[-1]) # Negative indices count from the end of the list; prints "2"

[3, 1, 2]
2 2


As mentioned, a list is not a mathematical array:

In [12]:
print(xs + [4, 5, 9])
print(3 * xs) 

[3, 1, 2, 4, 5, 9]
[3, 1, 2, 3, 1, 2, 3, 1, 2]


In [13]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [14]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

[3, 1, 'foo', 'bar']


In [15]:
x = xs.pop()     # Remove and return the last element of the list (since default value is -1)
print(x)
print(xs)

bar
[3, 1, 'foo']


There are two options to build an empty list:

In [16]:
x = []
x = list()

### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [17]:
nums = list(range(5)) # Notice: range(N) starts at 0 and ends with N-1 so the length of the array is N
nums

[0, 1, 2, 3, 4]

In [18]:
nums[2:4]    # Get a slice from index 2 to 4 (exclusive)

[2, 3]

In [19]:
nums[2:]     # Get a slice from index 2 to the end

[2, 3, 4]

In [20]:
nums[:2]     # Get a slice from the start to index 2 (exclusive)

[0, 1]

In [21]:
nums[:]      # Get a slice of the whole list

[0, 1, 2, 3, 4]

In [22]:
nums[:-1]    # Slice indices can be negative

[0, 1, 2, 3]

In [23]:
nums[0:4:2]  # Can also specify slice step size ([start:end:step_size])

[0, 2]

In [24]:
nums[2:4] = [8, 9] # Assign a new sublist to a slice
nums

[0, 1, 8, 9, 4]

In [25]:
# Two methods for deleting elements from a list
nums[0:1] = []
del nums[-1]
nums

[1, 8, 9]

### Loops

You can loop over the elements of a list in the manner shown below. **Notice the use of colon for loops, conditions, functions and classes**.

In [26]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [27]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print(f'#{idx+1}: {animal}')

#1: cat
#2: dog
#3: monkey


### List comprehensions

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [28]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
squares

[0, 1, 4, 9, 16]

You can make this code simpler using a list comprehension:

In [29]:
squares = [x ** 2 for x in nums]
squares

[0, 1, 4, 9, 16]

List comprehensions can also contain conditions:

In [30]:
even_squares = [x ** 2 for x in nums if x % 2 == 0]
even_squares

[0, 4, 16]

List comprehensions can be nested:

In [31]:
nums2 = [-1, 1]
[x * y for x in nums for y in nums2]

[0, 0, -1, 1, -2, 2, -3, 3, -4, 4]

What will be printed next?

In [32]:
arr = [3,6,8,0,1,2,1]
print([x for x in arr if x < 3]) 

[0, 1, 2, 1]


### Dictionaries

A dictionary stores key-value pairs. In other languages this is known as a *Map* or a *Hash*.

In [33]:
d = {'dog': 'cute', 'cat': 'evil'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary
print('cat' in d)     # Check if a dictionary has a given key

evil
True


In [34]:
d['fish'] = 'silence'    # Set an entry in a dictionary
d

{'dog': 'cute', 'cat': 'evil', 'fish': 'silence'}

In [35]:
# Trying to access a non-existing key raises a KeyError
try:
    d['monkey']
except KeyError as e:
    print(e, file=sys.stderr)

'monkey'


In [36]:
print(d.get('monkey', 'rr'))  # Get an element with a default
print(d.get('fish', 'N/A'))    # Get an element with a default

rr
silence


In [37]:
del d['fish']        # Remove an element from a dictionary
d

{'dog': 'cute', 'cat': 'evil'}

In [38]:
# Iteration over keys
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    print(f'A {animal} has {d[animal]} legs')

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [39]:
# Iterate over key-value pairs
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, num_legs in d.items():
    print(f'A {animal} has {num_legs} legs')

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [40]:
# Create a dictionary using the built-in dict() function
dict(foo=1, bar=2, baz=3)

{'foo': 1, 'bar': 2, 'baz': 3}

There are two options to build an empty dictionary:

In [41]:
d = {}
d = dict()

### Dictionary comprehensions

These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [42]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
even_num_to_square

{0: 0, 2: 4, 4: 16}

### Sets

A set is an un-ordered collection of **distinct** elements.

In [43]:
animals = {'cat', 'dog'}
print(animals)
print('cat' in animals )  # Check if an element is in a set
print('fish' in animals)  # prints "False"

{'cat', 'dog'}
True
False


In [44]:
animals.add('fish') # Add an element to a set
print('fish' in animals)
len(animals) # Number of elements in a set

True


3

In [45]:
animals.add('cat')       # Adding an element that is already in the set does nothing
animals

{'cat', 'dog', 'fish'}

_Loops_: Iterating over a set has the same syntax as iterating over a list; however **since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set**:

In [46]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print(f'#{idx+1}: {animal}')

#1: cat
#2: fish
#3: dog


An empty set is built as follows:

In [47]:
s = set()

### Set comprehensions

Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [48]:
from math import sqrt
s = {int(sqrt(x)) for x in range(37)}
s

{0, 1, 2, 3, 4, 5, 6}

### Tuples

A tuple is an **immutable** ordered list of values.

In [49]:
tup = (1, 2, 'three')
tup

(1, 2, 'three')

It can be used in some ways similar to a list:

In [50]:
tup[0:1], tup[1:3], tup[-1], len(tup)

((1,), (2, 'three'), 'three', 3)

A tuple can be used as a key in a dictionary and as an element of a set, while **list cannot**.

In [51]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
d

{(0, 1): 0,
 (1, 2): 1,
 (2, 3): 2,
 (3, 4): 3,
 (4, 5): 4,
 (5, 6): 5,
 (6, 7): 6,
 (7, 8): 7,
 (8, 9): 8,
 (9, 10): 9}

A tuple (and also a list) can be **unpacked**:

In [52]:
one, two, three = tup
print(one)
print(two)
print(three)

1
2
three


There are two options to build an empty tuple:

In [53]:
t = ()
t = tuple()

Note that when retuning multiple values from a function (or code block in a jupyter notebook, as above)
your values get wrapped in a tuple, and the tuple is what's returned.
Unpacking the returned value of a function can make it seems as if multiple values were returned as shown below.

## Functions

Python functions are defined using the `def` keyword. For example:

In [54]:
def sign(x):
    if x > 0:
        y = 1
        return 'positive', y
    elif x < 0:
        y = -1
        return 'negative', y
    else:
        y = 0
        return 'zero', y

for x in [-2, 0, 3]:
    print(sign(x))
    res, y = sign(x)
    print(res)
    print(y)

('negative', -1)
negative
-1
('zero', 0)
zero
0
('positive', 1)
positive
1


What will the next function return for the same `arr` ([3,6,8,0,1,2,1]) as before?

In [55]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

In [56]:
print(quicksort(arr))

[0, 1, 1, 2, 3, 6, 8]


We will often define functions to take optional keyword arguments, like this:

In [57]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s' % name.upper())
    else:
        print('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


### Small anonymus functions - lambda

A lambda function can take any number of arguments, but can only have a **single** expression.

In [58]:
f1 = lambda a, b : a * b
print(f1(10, 5)) 

f2 = lambda x:'mom' in x
example = ['kid', 'mom', 'dad']
print(f2(example))

f3 = lambda x: x.index('kid')
print(f3(example))

50
True
0


### Positional and Keyword arguments

Python functions are very flexible in the way they accept arguments. Both positional (regular) and keyword
arguments are supported and can be mixed in the same definition. Additionally, extra arguments can be passed in with the `*args` and `**kwargs` constructs.

Here's a function with three positional arguments and three keyword arguments which also accepts extra 
positional and keyword arguments.

In [59]:
def myfunc(a1, a2, a3, *extra_args, kw1='foo', kw2='bar', kw3=3, **extra_kwargs):
    print(f'Get positional args: {(a1, a2, a3)}')
    print(f'Get keyword args   : {dict(kw1=kw1, kw2=kw2, kw3=kw3)}')
    print(f'Get extra positional args: {extra_args}')
    print(f'Get extra keyword args: {extra_kwargs}')

It can be called in many ways:

In [60]:
myfunc(1, 2, 3, 4, 5, 6)

Get positional args: (1, 2, 3)
Get keyword args   : {'kw1': 'foo', 'kw2': 'bar', 'kw3': 3}
Get extra positional args: (4, 5, 6)
Get extra keyword args: {}


In [61]:
my_args = [1, 2, 3, 4, 5]
myfunc(*my_args)

Get positional args: (1, 2, 3)
Get keyword args   : {'kw1': 'foo', 'kw2': 'bar', 'kw3': 3}
Get extra positional args: (4, 5)
Get extra keyword args: {}


In [62]:
myfunc(1, 2, 3, kw3=3, kw2=2, dog='cute') # notice that it is possible to replace optional keyword arguments locations

Get positional args: (1, 2, 3)
Get keyword args   : {'kw1': 'foo', 'kw2': 2, 'kw3': 3}
Get extra positional args: ()
Get extra keyword args: {'dog': 'cute'}


In [63]:
my_kwargs = dict(kw1=1, kw2=2, kw3=3, kw4=4)
myfunc(1, 2, 3, **my_kwargs)

Get positional args: (1, 2, 3)
Get keyword args   : {'kw1': 1, 'kw2': 2, 'kw3': 3}
Get extra positional args: ()
Get extra keyword args: {'kw4': 4}


Note that keyword args can be omitted, while positional args cannot:

In [64]:
try:
    myfunc(1,2)
except TypeError as e:
    print(e, file=sys.stderr)

myfunc() missing 1 required positional argument: 'a3'


## Classes
Python is an *object oriented programming (OOP)* language. We can create objects  by *classes* and define *attributes* and *methods* to every one of them. `__init__` defines the *constructor* of the class in Python.

In [65]:
class Greeter:
    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
            self.m = 1
        else:
            print('Hello, %s' % self.name)
            self.m = 0
            
    def greetback(self):
        if self.m == 1:
            print('HELLO TO YOU TOO!')

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method
g.greetback()
g.greet(loud=True)   # Call an instance method
g.greetback()

Hello, Fred
HELLO, FRED!
HELLO TO YOU TOO!


## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

If you have previous knowledge in Matlab,
we recommend the [numpy for Matlab users](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html) page as a useful resource.

To use Numpy, we first need to import the `numpy` package:

In [66]:
import numpy as np

### Arrays

A numpy array represents an n-dimentional grid of values (matrix), all of the same type, and is indexed by a tuple of nonnegative integers.

- The number of dimensions is the **rank** of the array.
- The **shape** of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [67]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(f'shape={a.shape},   a[1]={a[1]},   type={type(a)}')

a[0] = 5                 # Change an element of the array
a

shape=(3,),   a[1]=2,   type=<class 'numpy.ndarray'>


array([5, 2, 3])

In [68]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)
print('shape =', b.shape)

[[1 2 3]
 [4 5 6]]
shape = (2, 3)


In [69]:
b[0, 0], b[0, 1], b[1, 0]

(np.int64(1), np.int64(2), np.int64(4))

Numpy also provides many functions to create arrays:

In [70]:
np.zeros((2,2))  # Create an array of all zeros

array([[0., 0.],
       [0., 0.]])

In [71]:
np.zeros_like(b)  # Create an array of zeors with the same shape as b

array([[0, 0, 0],
       [0, 0, 0]])

In [72]:
np.ones((10,1))   # Create an array of all ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [73]:
np.full((3,3), 7.2) # Create a constant array

array([[7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2],
       [7.2, 7.2, 7.2]])

In [81]:
np.eye(4, dtype=int) # Create an identity matrix of integers

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [82]:
t = np.random.random((4,4,3)) # Create a 3d-array filled with random values
t

array([[[0.74853161, 0.55755368, 0.47101364],
        [0.75286784, 0.41980101, 0.74494794],
        [0.84111825, 0.95185681, 0.69193454],
        [0.47814539, 0.40786601, 0.17747784]],

       [[0.80126097, 0.26719441, 0.20931034],
        [0.55708363, 0.85215826, 0.02274653],
        [0.38427454, 0.99004086, 0.54382826],
        [0.22219855, 0.17207812, 0.39238587]],

       [[0.95506727, 0.3946294 , 0.34185935],
        [0.21303574, 0.44939769, 0.1427529 ],
        [0.76060762, 0.13232787, 0.94227749],
        [0.52580348, 0.48087641, 0.5550848 ]],

       [[0.25193949, 0.09043744, 0.71759862],
        [0.6495723 , 0.24404612, 0.99751361],
        [0.50974888, 0.55230639, 0.00324211],
        [0.95794605, 0.45420131, 0.56321374]]])

In [83]:
t[1,1,2]

np.float64(0.022746527480671297)

### Rank-1 Arrays

In `numpy` **rank-1** arrays of length `n` have a shape of `(n,)`. Such arrays are somewhat special in that `numpy` can treat them both as column or as row vectors. The main difference between an array with the shape of `(n,)` and an array with the shape `(n,1)` (or `(1,n)`) is that *rank-1* array can only be accessed by **one index** where *rank-2* has to be accessed only by **two indices**. 



In [84]:
# A rank-1 array
a1 = np.array([1,2,3])
print(f'\n a1 {a1.shape}:\n', a1)

# A column vector (1 for column and -1 for rows (-1 tells python 'derive it by yourself'))
a_col = a1.reshape(-1, 1)
print(f'\n a_col {a_col.shape}:\n', a_col)

# A row vector (1 for row and -1 for columns)
a_row = a1.reshape(1, -1)
print(f'\n a_row {a_row.shape}=\n', a_row)


 a1 (3,):
 [1 2 3]

 a_col (3, 1):
 [[1]
 [2]
 [3]]

 a_row (1, 3)=
 [[1 2 3]]


Rank-1 arrays have different semantics when using them in a vector-vector or a vector-matrix products, so always make sure you know what shapes you're working with:

In [85]:
print('\n a1 * a1 =', np.dot(a1, a1))  # or a1 @ a1

print('\n a_row * a1 =', a_row @ a1)

print('\n a1 * a_col =', a1 @ a_col)

print('\n a_row * a_col =', a_row @ a_col)

print('\n a_col * a_row =\n', a_col @ a_row)



 a1 * a1 = 14

 a_row * a1 = [14]

 a1 * a_col = [14]

 a_row * a_col = [[14]]

 a_col * a_row =
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


## Array indexing

Numpy offers several ways to index into arrays.

### **Slicing**

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify **a slice for each dimension** of the array:

In [86]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


**Important:** A slice of an array is a **view** into the same in-memory data, so modifying it will modify the original array.

In [88]:
b[0, 0] = 77777
a

array([[    1, 77777,     3,     4],
       [    5,     6,     7,     8],
       [    9,    10,    11,    12]])

But if we wrote the followin for instance

In [89]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
b = a[:2, 1:3]
b = 2*b
print(b)

[[ 4  6]
 [12 14]]


In [91]:
b[0, 0] = 77777
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can also mix integer indexing with slice indexing.
However, doing so will yield an array of **lower rank** than the original array.

Note that this is quite different from the way that MATLAB handles array slicing.

In [92]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [93]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a

print(row_r1, 'shape=', row_r1.shape)
print(row_r2, 'shape=', row_r2.shape)
print(row_r3, 'shape=', row_r3.shape)

[5 6 7 8] shape= (4,)
[[5 6 7 8]] shape= (1, 4)
[[5 6 7 8]] shape= (1, 4)


In [94]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### **Integer array indexing** 

- When you slice, the resulting array view will always be a subarray of the original array.
- Integer array indexing allows you to construct arbitrary arrays using data from another array.


In [95]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [96]:
# An example of integer array indexing.
# The returned array will have shape (3,)
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [97]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [98]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [99]:
# Create an array of indices
b = np.array([0, 2, 0, 1])
print(np.arange(4))
print(b)

# Select one element from each row of a using the indices in b
a[np.arange(4), b]

[0 1 2 3]
[0 2 0 1]


array([ 1,  6,  7, 11])

In [100]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 1000
a

array([[1001,    2,    3],
       [   4,    5, 1006],
       [1007,    8,    9],
       [  10, 1011,   12]])

### **Boolean array indexing**

This type of indexing is used to select the elements of an array that satisfies some condition
(similar to MATLAB's logical indexing).

In [101]:
a = np.array([[1,2], [3, 4], [5, 6]])
print('a=\n', repr(a))
bool_idx = (a > 2)  # Find the elements of 'a' that are larger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as 'a', where each slot of bool_idx tells
                    # whether that element is greater than 2.

bool_idx

a=
 array([[1, 2],
       [3, 4],
       [5, 6]])


array([[False, False],
       [ True,  True],
       [ True,  True]])

In [102]:
# We use boolean-array-indexing to construct a rank 1 array
# consisting of the elements of 'a' corresponding to the True values
# of bool_idx
a[a>2]

array([3, 4, 5, 6])

For brevity we have left out a lot of details regarding numpy array indexing; if you wish to know more you can read the [documentation](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html).

### Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [103]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

x.dtype, y.dtype, z.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Math array

### Elementwise operations
Basic mathematical functions **operate elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module:

In [104]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [105]:
# Elementwise difference
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [106]:
# Elementwise product
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [107]:
# Elementwise division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [108]:
# Elementwise square root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


There are of course many more elementwise operations implemented by `numpy`.

### Inner products

Unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication (as we mentioned above).

We instead use the `dot()` function to:
- compute inner products of vectors.
- multiply a vector by a matrix.
- multiply matrices.

The `dot()` function is available both as a function in the numpy module and as an instance
method of array objects.

In [109]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [110]:
X = np.array([[1,2],[3,4]])
print('X =\n', repr(X)) # The repr() function returns a printable representation of the given object.

# Matrix-vector product; produce a rank 1 array
print('Xv =', x.dot(v))

X =
 array([[1, 2],
       [3, 4]])
Xv = [29. 67.]


In [111]:
# Matrix-matrix product; produces a rank 2 array
Y = np.array([[5,6],[7,8]])
print('Y= \n', repr(Y))

print('XY =\n', X.dot(Y))

Y= 
 array([[5, 6],
       [7, 8]])
XY =
 [[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [112]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements
print(np.sum(x, axis=0))  # Compute sum of each column
print(np.sum(x, axis=1) ) # Compute sum of each row

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to **reshape** or otherwise manipulate data in arrays.

In [113]:
# Transpose
print(x)
print(x.T)
print(np.transpose(x))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [114]:
v = np.array([1,2,3]) # rank 1
print(v.reshape(1, -1)) # row vector
print(v.reshape(-1, 1)) # column vector

[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of **different shapes** when performing arithmetic operations.

Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. \
We could do it like this:

In [115]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

This would work; however when the matrix `x` is very large, computing an explicit loop in Python could be slow.\
Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [116]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
vv

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [117]:
y = x + vv  # Add x and vv elementwise
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. \
Consider this version, using broadcasting:

In [118]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting

print('shapes: ', x.shape, v.shape)
y

shapes:  (4, 3) (3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. All input arrays with `ndim` smaller than the input array of largest ndim, have 1’s prepended to their shapes.
1. The size in each dimension of the output shape is the maximum of all the input sizes in that dimension.
1. An input can be used in the calculation if its size in a particular dimension either matches the output size in that dimension, or if it's equal 1.
1. If an input has a dimension of size 1 in its shape, the first data entry in that dimension will be used for all calculations along that dimension. In other words, the stepping machinery of the ufunc will simply not step along that dimension (the stride will be 0 for that dimension).


For further explanation, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [119]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has a shape of (3,)
w = np.array([4,5])    # w has a shapeof (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [120]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x)
x * 2

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

Broadcasting typically makes your code more concise and faster, so you should strive to use it wherever possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

#### *Credit: Some parts of this tutorial were adapted from the [CS231n Python tutorial](http://cs231n.github.io/python-numpy-tutorial/) by Justin Johnson and from a tutorial written by Aviv Rosenberg. The tutorial was written with the assitance of [Moran Davoodi](mailto:morandavoodi@gmail.com), [Yuval Ben Sason](mailto:yuvalbse@gmail.com) and Kevin Kotzen*